### ISSUE TITLE
Unlimited transforms

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#126]
Currently the "Transformation" for a surface only allows change of the yaw.
It shall be possible to rotate it in an unlimited manner (as first instance by keyboard input), i.e. also changing pitch and roll of a surface. That way it would be possible to manually align any surfaces w.r.t. each other.
It would be beneficial if the rotation centre could remain close to the (already translated) surface to be transformed.

The current "yaw only" mode of existing .pro3d files shall be further supported, i.e. when an existing yaw is given, it shall be applied in the same manner as for previous PRo3D versions.

**Comment by ThomasOrtner** [comment]
There was a reason we limited this to yaw, because the up vector is always clear and we can intuitively rotate around it. Which axes do we want to use for pitch (around right/East) and roll (around forward/North) and how do the rotation transformations affect these axes, e.g. yaw also turns right and forward. And how do we maintain the reproducibility of these transformations via Euler angles? Translation should still be along north, east, up I guess.

**Comment by gpaar** [comment]
transformation in N/E/U is ok as current. Yaw shall be first oder, then pitch, then roll (i.e. if a rover would turn left/right, then enter a slope after turning, and then on the slope rolls sideways).

**Comment by ThomasOrtner** [comment]
perfect, I think that should be doable, although these are famous last words when working with transformations 😅

**Comment by gpaar** [comment]
Just make sure that the rotation centre walks with the translated model, otherwise it's getting cumbersome. Would be nice to be able to export e.g. quaternions or similar for an obtained transform.

**Comment by gpaar** [comment]
Redundant and already resolved
