### ISSUE TITLE
Zooming enhancements

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#261]
- [x] store frustum settings in scene
- [x] make it a global setting that always applies, get rid of the flag
- [x] screen space scaling for text labels when using focal length
- [x] set range of the focal length to 10-1000 

include frustum settings (focal length / sensor size / horizontal field of view) in 
- [ ] regular bookmarks, 
- [x] sequenced bookmarks
- [x] batch rendering

------ Original Issue Description 
- Incorporate the selection of the Frustrum settings into sequence bookmarks
- Same as for position, also smoothly change the zoom value of Frustrum
- Extend the frustrum zoom values from current setting without frustrum flag set (or even less = more wide angle) to 300 or so
- Incorporate frustrum setting also into bookmarks
- Graphical elements (annotations etc., such as the dimension number of coordinate system) shall not zoom with frustrum settings
- Interpolate between zoom settings in Sequenced Bookmarks

**Comment by RebeccaNowak** [comment]
@gpaar We need some clarification for this task:

1. By Frustum Settings, do you mean specifically the settings for the focal length - "use Focal" and "Focal (mm)"?
![image](https://github.com/pro3d-space/PRo3D/assets/35483671/282c02fe-d946-4e05-b1f1-12b9116afc7c)
2. "_Extend the frustrum zoom values from current setting without frustrum flag set (or even less = more wide angle) to 300 or so_" - By "frustum zoom values", do you mean the focal length as seen in the screenshot above? Currently the minimum for the focal length is 28 and the maximum is 100. Should we set the maximum to 300? Should we change the minimum, and if yes what value would be appropriate?
3. "_Graphical elements (annotations etc., such as the dimension number of coordinate system) shall not zoom with frustrum settings_" This is problematic, because if the frustum is different for e.g. annotations and surfaces, annotations will not be in the correct location on the surface. What is your goal here? What visual effect do you want to achieve?

**Comment by gpaar** [comment]
1. To me "use Focal" could be obsolete, if a Focal (mm) value is always present and can be modified. However, "mm" is not a unique setting anyway. I suggest to place a second value (globally to apply to a scene) that also specifies the physical size of a "detector" (screen, that is) pixel in microns. This way, it would be possible to replicate the optical features of a specific camera. Default could be something like 20mm and 7.4 Microns (the latter is Mastcam-Z's pixel size on the CCD, see  https://mars.nasa.gov/mars2020/spacecraft/instruments/mastcam-z/for-scientists/). As a "nice-to-have" an alternative setting could make good sense, namely the diameter of the (horizontal) field-of-view. This would disable the selection of mm and microns.
2. Do we need minimum and maximum at all? If so, I suggest 10-1000 [mm] and 1-100 [microns] and for the "nice-to-have" above 0.1 - 179 [degrees]
3.  Only the character size is meant: It shall not zoom but remain constant in screen coordinates. The annotations themselves (polygons, scale bars, etc.) shall zoom in a consistent manner with the surface. The width of vectors shall not zoom either but remain constant in screen space.

**Comment by gpaar** [comment]
Remaining items will get a new issue
